name: BanCID
main: BanCID\BanCID
version: 0.9.0-alpha
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]

author: kenygamer
description: A PocketMine-MP plugin to manage device/client ID bans

permissions:
 bancid.command:
  description: Allows access to all BanCID commands.
  default: false
  children:
   bancid.command.bancid:
    description: Allows access to the BanCID bancid command.
    default: op
   bancid.command.unbancid:
    description: Allows access to the BanCID unbancid command.
    default: op
   bancid.command.bancidlist:
    description: Allows access to the BanCID bancidlist command.
    default: op
